#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Checking Code Format, with prettier... "
npm run prettier-check
echo "Checking Cloud Formation Style, with cfn-lint "
cfn-lint -t ./template.yml
echo "Checking Code Style, with eslint"
npm run lint
echo "You are able to run auto fix commands for prettier and eslint errors. If failed check out the package.json"