name: Deploying GSSAR
"on":
  push:
    branches:
      - main
      - ft/**
      - bug/**
      - hotfix/**
      - release/**
jobs:
  DeployStack:
    runs-on: ubuntu-latest
    env:
      REGION: us-east-1
    environment: main
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Setup AWS SAM
        uses: aws-actions/setup-sam@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws-region: "${{ env.REGION }}"
      - name: Install and Build Function (authorizerQueueFilter)
        run: |
          cd ./functions/authorizers/authorizerQueueFilter 
          npm cache clean --force
          npm install
          npm run build
      - name: Install and Build Function (GithubWebhookSecretValidator)
        run: |
          cd ./functions/authorizers/githubWebhookSecretValidator 
          npm cache clean --force
          npm install
          npm run build
      - name: Install and Build Function (CreateDBRecord)
        run: |
          cd ./functions/helpers/createDBRecord
          npm cache clean --force
          npm install
          npm run build
      - name: Install and Build Function (UpdateDBRecord)
        run: |
          cd ./functions/helpers/updateDBRecord
          npm cache clean --force
          npm install
          npm run build
      - name: Install and Build Function (HandleDBRecordEvent)
        run: |
          cd ./functions/helpers/handleDBRecordEvent
          npm cache clean --force
          npm install
          npm run build
      - name: Install and Build Function (AllTableStreamEventHandler)
        run: |
          cd ./functions/helpers/allTableStreamEventHandler
          npm cache clean --force
          npm install
          npm run build
      - name: Install and Build Function (streamRepoOverviewEventSendToSQS)
        run: |
          cd ./functions/helpers/streamRepoOverviewEventSendToSQS
          npm cache clean --force
          npm install
          npm run build
      - name: Install and Build Function (insertDataIntoOrganisationOverviewTable)
        run: |
          cd ./functions/helpers/insertDataIntoOrganisationOverviewTable
          npm cache clean --force
          npm install
          npm run build
      - name: SAM Build
        run: sam build --use-container
      - name: SAM Deploy
        shell: bash
        run: |
          branch=$(git rev-parse --abbrev-ref HEAD)
          echo "Current branch is: $branch"
          formattedBranch=$(echo $branch | sed -e 's/\//-/g')
          echo "Formatted branch is: $formattedBranch"
          stackName="gcsmttr-$formattedBranch"
          echo "Stack name: $stackName"
          sam deploy --debug --no-confirm-changeset --no-fail-on-empty-changeset --stack-name "$stackName" --capabilities CAPABILITY_IAM --region ${{ env.REGION }} --resolve-s3
