name: Testing GSSAR
'on':
  push:
    branches:
      - main
      - ft/**
      - bug/**
      - hotfix/**
      - release/**
  pull_request:
    branches:
      - main
      - ft/**
      - bug/**
      - hotfix/**
      - release/**
jobs:
  CodeQL:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
      - name: Autobuild
        uses: github/codeql-action/autobuild@v1
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
  LintCloudFormation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2
      - name: Print the Cloud Formation Linter Version & run Linter.
        run: |
          cfn-lint -t ./template.yml
